---
- hosts: all
  tasks:
    - name: install apt-transport-https
      apt: 
        name: apt-transport-https
        update_cache: yes
    - name: install ca-certificates
      apt:
        name: ca-certificates
    - name: install curl
      apt:
        name: curl
    - name: install software-properties-common
      apt:
        name: software-properties-common
    - name: install GPG ca-certificates
      shell: curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
    - name: add apt repository
      shell: sudo add-apt-repository "deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
    - name: install docker-ce
      shell: apt install -y docker-ce=17.03.2~ce-0~ubuntu-xenial --allow-downgrades
