version: '2'
services:
  rabbit1:
    image: rabbitmq:3.7-management
    hostname: rabbit1
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE='rabbitcookie'
  rabbit2:
    image: rabbitmq:3.7-management
    hostname: rabbit2
    restart: always
    links:
      - rabbit1
    ports:
      - "5673:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE='rabbitcookie'
  rabbit3:
    image: rabbitmq:3.7-management
    hostname: rabbit3
    restart: always
    links:
      - rabbit1
      - rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE='rabbitcookie'
    ports:
      - "5674:5672"
